import Category from './models/Category';
import Meal from './models/Meal';
import Colors from './assets/Colors';

export const CATEGORIES = [
    new Category(1, 'Indian', Colors.grid1),
    new Category(2, 'Italian', Colors.grid2),
    new Category(3, 'Thai', Colors.grid3),
    new Category(4, 'Continental', Colors.grid1),
    new Category(5, 'Chinese', Colors.grid2),
    new Category(6, 'South Indian', Colors.grid3),
    new Category(7, 'Snacks', Colors.grid1),
    new Category(8, 'Grill', Colors.grid2),
    new Category(9, 'Brunch', Colors.grid3),
    new Category(10, 'Exotic Soups', Colors.grid1)
]

export const MEALS = [
    new Meal(100,1,'Butter Chicken','Butter Chicken or murgh makhani is a curry of chicken in a spiced tomato, butter and cream sauce. It originated in India as a curry. It is similar to chicken tikka masala, which uses a tomato gravy.','https://images.pexels.com/photos/6113813/pexels-photo-6113813.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',449,false),
    new Meal(101,1,'Samosa','A samosa is a South Asian fried or baked pastry with a savory filling like spiced potatoes, onions, peas, beef and other meats, or lentils. It may take different forms, including triangular, cone, or half-moon shapes, depending on the region.','https://images.pexels.com/photos/2474658/pexels-photo-2474658.jpeg?auto=compress&cs=tinysrgb&dpr=3&h=750&w=1260',79,true),
    new Meal(102,1,'Chicken Biryani','Biryani is a mixed rice dish originating among the Muslims of the Indian subcontinent. It is made with Indian spices, rice, and meat, and sometimes, in addition, eggs and/or vegetables such as potatoes in certain regional varieties. Biryani is popular throughout the Indian subcontinent, as well as among its diaspora.','https://images.pexels.com/photos/1624487/pexels-photo-1624487.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',249,false),
    new Meal(103,1,'Kadhai Paneer','Shahi paneer is a preparation of paneer, native to the Indian subcontinent, consisting of a thick gravy of cream, tomatoes and Indian spices.','https://images.pexels.com/photos/2474661/pexels-photo-2474661.jpeg?auto=compress&cs=tinysrgb&dpr=3&h=750&w=1260',420,true),
    new Meal(104,1,'Butter Naan','Naan is a leavened, oven-baked flatbread found in the cuisines mainly of Western Asia, South Asia, Indonesia, Myanmar and the Caribbean.','https://images.pexels.com/photos/1117862/pexels-photo-1117862.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',60,true),
    new Meal(105,2,'Margeritta Pizza','Pizza is a savory dish of Italian origin consisting of a usually round, flattened base of leavened wheat-based dough topped with tomatoes, cheese, and often various other ingredients, which is then baked at a high temperature, traditionally in a wood-fired oven. A small pizza is sometimes called a pizzetta.','https://images.pexels.com/photos/5088590/pexels-photo-5088590.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',299,true),
    new Meal(106,2,'Chicken Pizza','Pizza is a savory dish of Italian origin consisting of a usually round, flattened base of leavened wheat-based dough topped with tomatoes, cheese, and often various other ingredients, which is then baked at a high temperature, traditionally in a wood-fired oven. A small pizza is sometimes called a pizzetta.','https://images.pexels.com/photos/315755/pexels-photo-315755.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',99,false),
    new Meal(107,2,'White Sauce Pasta','Pasta is a type of food typically made from an unleavened dough of wheat flour mixed with water or eggs, and formed into sheets or other shapes, then cooked by boiling or baking.','https://images.pexels.com/photos/1487511/pexels-photo-1487511.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',299,true),
    new Meal(108,3,'Thai Panang Curry','Panang curry is rich and creamy, spicy yet balanced, with underlying notes of peanut and coconut. I make my panang curry with lots of bell peppers and carrots, and optional tofu for extra protein. Its a perfectly satisfying weeknight meal for cold days.','https://images.pexels.com/photos/1437590/pexels-photo-1437590.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',180,false),
    new Meal(110,3,'Sushi','Sushi is a traditional Japanese dish of prepared vinegared rice, usually with some sugar and salt, accompanying a variety of ingredients, such as seafood, often raw, and vegetables. Styles of sushi and its presentation vary widely, but the one key ingredient is "sushi rice", also referred to as shari, or sumeshi.','https://images.pexels.com/photos/6984182/pexels-photo-6984182.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',199,false),
    new Meal(109,3,'Chicken lettuce Salad','Delicious tasty tender Chicken Salad','https://images.pexels.com/photos/991967/pexels-photo-991967.jpeg?auto=compress&cs=tinysrgb&dpr=3&h=750&w=1260',200,false),
    new Meal(111,4,'Garlic Noodles','Chow mein are Chinese stir-fried noodles with vegetables and sometimes meat or tofu; the name is a romanization of the Taishanese chāu-mèn. The dish is popular throughout the Chinese diaspora and appears on the menus of most Chinese restaurants abroad. It is particularly popular in India, Nepal, the UK, and the US.','https://images.pexels.com/photos/1279330/pexels-photo-1279330.jpeg?auto=compress&cs=tinysrgb&dpr=3&h=750&w=1260',299,true),
    new Meal(112,4,'Macaroni','Pasta is a type of food typically made from an unleavened dough of wheat flour mixed with water or eggs, and formed into sheets or other shapes, then cooked by boiling or baking.','https://images.pexels.com/photos/1437267/pexels-photo-1437267.jpeg?auto=compress&cs=tinysrgb&dpr=3&h=750&w=1260',299,true),
    new Meal(113,5,'Chicken Momos','Momo is a type of East and South Asian steamed filled dumpling. Momo is native to Tibet, Nepal, Bhutan as well as Indian Himalayan Region of Ladakh, Sikkim, Assam, and Arunachal Pradesh, Himachal Pradesh, Uttarakhand, and Darjeeling. It is popular across a wider region of the Indian subcontinent.','https://images.pexels.com/photos/5409009/pexels-photo-5409009.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',299,false),
    new Meal(114,5,'Veg Momos','Momo is a type of East and South Asian steamed filled dumpling. Momo is native to Tibet, Nepal, Bhutan as well as Indian Himalayan Region of Ladakh, Sikkim, Assam, and Arunachal Pradesh, Himachal Pradesh, Uttarakhand, and Darjeeling. It is popular across a wider region of the Indian subcontinent.','https://images.pexels.com/photos/3926123/pexels-photo-3926123.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',299,true),
    new Meal(115,6,'Dosa Sambhar','A dosai or dosa or dose is a thin pancake or crepe, originating from South India, made from a fermented batter predominantly consisting of lentils and rice. It is somewhat similar to a crepe in appearance, although savoury flavours are generally emphasized.','https://images.pexels.com/photos/941869/pexels-photo-941869.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',299,false),
    new Meal(116,7,'Tandori Chicken','Barbecue chicken consists of chicken parts or entire chickens that are barbecued, grilled or smoked. There are many global and regional preparation techniques and cooking styles. Barbecue chicken is often seasoned or coated in a spice rub, barbecue sauce, or both.','https://images.pexels.com/photos/106343/pexels-photo-106343.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',299,false),
    new Meal(117,7,'Corn Gravy','Delicious tasty tender Chicken','https://images.pexels.com/photos/2679501/pexels-photo-2679501.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',299,true),
    new Meal(118,8,'Grilled Chicken','Barbecue chicken consists of chicken parts or entire chickens that are barbecued, grilled or smoked. There are many global and regional preparation techniques and cooking styles. Barbecue chicken is often seasoned or coated in a spice rub, barbecue sauce, or both.','https://images.pexels.com/photos/5491044/pexels-photo-5491044.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',450,false),
    new Meal(119,9,'Special Chicken Sandwich','A chicken sandwich is a sandwich that typically consists of boneless, skinless chicken breast served between slices of bread, on a bun, or on a roll. Variations on the "chicken sandwich" include the chicken burger or chicken on a bun, hot chicken, and chicken salad sandwich.','https://images.pexels.com/photos/5337811/pexels-photo-5337811.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',300,false),
    new Meal(120,10,'Exotic Mushroom Soup','Cream of mushroom soup is a simple type of soup where a basic roux is thinned with cream or milk and then mushrooms and/or mushroom broth are added. It is well known in North America as a common type of condensed canned soup. Cream of mushroom soup is often used as a base ingredient in casseroles and comfort foods.','https://images.pexels.com/photos/4103375/pexels-photo-4103375.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',199,true),
    new Meal(121,10,'Chicken Aromatica Soup','Chicken soup is a soup made from chicken, simmered in water, usually with various other ingredients. The classic chicken soup consists of a clear chicken broth, often with pieces of chicken or vegetables; common additions are pasta, noodles, dumplings, or grains such as rice and barley.','https://images.pexels.com/photos/2133989/pexels-photo-2133989.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',199,false)
]